# Generated by Django 5.2 on 2026-04-01 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description_short', models.CharField(default='Краткое описание', max_length=800, verbose_name='Краткое описание')),
                ('description_long', models.TextField(default='Описание', verbose_name='Описание')),
                ('lat', models.DecimalField(decimal_places=16, default=0.0, max_digits=20, max_length=20, verbose_name='Широта')),
                ('lng', models.DecimalField(decimal_places=16, default=0.0, max_digits=20, max_length=20, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/', verbose_name='Картинка')),
                ('order', models.PositiveIntegerField(default=0)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
