# Generated by Django 5.2 on 2026-04-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='lng',
            new_name='longitude',
        ),
    ]
