# Generated by Django 5.2 on 2026-04-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_remove_place_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='text',
        ),
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=models.TextField(default='Описание', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='description_short',
            field=models.CharField(default='Краткое описание', max_length=800, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, max_length=20, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10, max_length=20, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
