# Generated by Django 5.2 on 2026-04-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_text_place_description_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20, max_length=20, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20, max_length=20, verbose_name='Долгота'),
        ),
    ]
