# Generated by Django 5.2 on 2026-04-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='short_description',
            field=models.TextField(blank=True, default='Краткое описание', verbose_name='Краткое описание'),
        ),
    ]
