# Generated by Django 5.2 on 2026-04-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_placeimage_order_alter_placeimage_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок отображения'),
        ),
    ]
